services:
  #gatway
  gatway:
    build: ./gatway
    container_name: gatway
    restart: unless-stopped
    ports:
      - ${GATWAY_PORT}:${GATWAY_PORT}
    environment:
      - PORT=${GATWAY_PORT}
    depends_on:
      - vacancy
      - profile
      - authentication
    networks:
      - netservices

  #vacancy service:
  vacancy:
    build: ./service/vacancy
    container_name: vacancy
    restart: unless-stopped
    ports:
      - ${VACANCY_PORT}:${VACANCY_PORT}
    environment:
      - POSTGRES_PASSWORD=${VACANCY_DB_PASSWORD}
      - PORT=${VACANCY_PORT}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
    depends_on:
      - vacancy_db
    networks:
      - netservices
  vacancy_db:
    image: postgres:latest
    container_name: vacancy_db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${VACANCY_DB_PASSWORD}
      - PORT=${VACANCY_PORT}
    volumes:
      - vacancy:/var/lib/postgresql/data
    networks:
      - netservices

  #profile service:
  profile:
    build: ./service/profile
    container_name: profile
    restart: unless-stopped
    ports:
      - ${PROFILE_PORT}:${PROFILE_PORT}
    environment:
      - POSTGRES_PSASWORD=${PROFILE_DB_PASSWORD}
      - PORT=${PROFILE_PORT}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
    networks:
      - netservices
  profile_db:
    image: postgres:latest
    container_name: profile_db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${PROFILE_DB_PASSWORD}
    volumes:
      - profile:/var/lib/postgresql/data
    networks:
      - netservices
  
  #authentication service:
  authentication:
    build: ./service/authentication
    container_name: authentication
    restart: unless-stopped
    ports:
      - ${AUTHENTICATION_PORT}:${AUTHENTICATION_PORT}
    environment:
      - REFRESH_TOKEN=${REFRESH_TOKEN}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - PORT=${AUTHENTICATION_PORT}
      - PROFILE_URL=${PROFILE_URL}
    networks:
      - netservices

volumes:
  vacancy:
  profile:

networks:
  netservices:
    driver: bridge
